name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build_bluepill_examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install target
      run: rustup target add thumbv7m-none-eabi
    - name: Build Bluepill examples
      working-directory: examples/bluepill
      run: cargo build --verbose --release

  build_rp_pico_examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install target
        run: rustup target add thumbv6m-none-eabi
      - name: Build rp-pico examples
        working-directory: examples/rp-pico
        run: cargo build --verbose --release

  build_arduino_examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-07-10
          override: true
          components: rust-src
      - name: Install avr-gcc, binutils, and libc
        run: sudo apt-get install -y avr-libc binutils-avr gcc-avr
      - name: Build arduino examples
        working-directory: examples/arduino_uno
        run: cargo build --verbose --release
